controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_missions_by_statut:
    path: /missions/{statut}
    controller: App\Controller\MissionsController::getMissionsByStatut
    methods: [GET]

app_missions_new:
    path: /missions/new
    controller: App\Controller\MissionsController::new
    methods: [GET]

#Page par defaut